services:
  kafka:
    image: wurstmeister/kafka
    environment:
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_MESSAGE_MAX_BYTES=2000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=2000000
      - KAFKA_FETCH_MAX_BYTES=2000000
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - mynetwork


  zookeeper:
    image: wurstmeister/zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - "2181:2181"
    networks:
      - mynetwork

  rest:
    build:
      context: ./rest
    ports:
      - "8080:8080"
    depends_on:
      - kafka
      - zookeeper
    environment:
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    networks:
      - mynetwork
    volumes:
      - ./logs:/logs

networks:
  mynetwork:
    driver: bridge
